sign-commit = true
push-remote = "origin"
pre-release-commit-message = "Release version {{version}}"
tag-message = "Release {{version}}"
tag-name = "v{{version}}"
publish = false
allow-branch = ["main"]
